.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CRAWLER\-SEED" "5" "March 2017" "IBM " "IBM Data Crawler Manual"
Seeds are the starting points of a crawl, and are used by the data crawler to retrieve data from the resource that is identified by that seed\. Typically, seeds configure URLs to access protocol\-based resources such as fileshares, SMB shares, databases, and other data repositories that are accessible by various web protocols\. Moreover, different seed URLs have different capabilities\.
.
.P
Seeds can also be repository\-specific, to enable crawling of specific third\-party applications such as customer relationship management (CRM) systems, product life cycle (PLC) systems, content management systems (CMS), cloud\-based applications, and web database applications\.
.
.P
The data crawler currently provides crawl seeds that support file connectors for the following repository types:
.
.IP "\(bu" 4
Filesystem
.
.IP "\(bu" 4
Databases, via JDBC
.
.IP "\(bu" 4
CMIS (Content Management Interoperability Services)
.
.IP "\(bu" 4
SMB (Server Message Block), CIFS (Common Internet Filesystem), or Samba fileshares
.
.IP "\(bu" 4
SharePoint and SharePoint Online
.
.IP "\(bu" 4
Box
.
.IP "" 0
.
.P
A crawl seed configuration template is also provided, which allows you to customize a crawl seed for a custom connector\.
.
.SH "Getting started:"
When crawling data repositories, the crawler begins at a user\-specified seed URL, and begins downloading pages of information\. The crawler also locates links in the downloaded pages, and schedules the newly\-discovered pages for further crawling\.
.
.P
Configuration information is used to determine which pages need to be crawled, and how to crawl them\. This file explains the options that you can configure for each connector\'s crawl seed file\.
.
.P
\fBNote\fR: Each crawl seed configuration file works with a corresponding file connector configuration file; file connector options are described separately\.
.
.SS "Configuring the Filesystem Crawl Seed"
The following values can be configured for the Filesystem crawl seed file\. To set these values, open the file \fBconfig/seeds/filesystem\-seed\.conf\fR and specify the following values specific to your use cases:
.
.IP "\(bu" 4
\fBurl\fR \- Newline\-separated list of files and folders to crawl\. UNIX users can use a path such as \fB/usr/local/\fR\. The URLs must start with \fBsdk\-fs://\fR\. So to crawl, for example, \fB/home/watson/mydocs\fR, the value of this URL would be \fBsdk\-fs:///home/watson/mydocs\fR \- the third \fB/\fR is necessary! \fBNote\fR: The Filesystem connector uses a custom protocol, \fBsdk\-fs://\fR, to create a valid URL\. Do not prepend \fBfile://\fR to the listed paths; the URLs must start with \fBsdk\-fs://\fR\.
.
.IP "\(bu" 4
\fBhops\fR \- Internal use only\.
.
.IP "\(bu" 4
\fBdefault\-allow\fR \- Internal use only\.
.
.IP "" 0
.
.SS "Configuring the Database Crawl Seed"
The following values can be configured for the Database crawl seed file\. To set these values, open the file \fBconfig/seeds/database\-seed\.conf\fR and specify the following values specific to your use cases:
.
.IP "\(bu" 4
\fBurl\fR \- The URL of the table or view to retrieve\. Defines your custom SQL database seed URL\. The structure is:
.
.IP
\fBdatabase\-system://host:port/database?[per=num]&[sql=SQL]\fR
.
.IP
Testing a seed URL will show all of the enqueued URLs\. For example, testing the following URL for a database containing 200 records:
.
.IP
\fBsqlserver://test\.mycompany\.com:1433/WWII_Navy/?per=100&sql=select%20*%20from%20vessel&\fR
.
.IP
shows the following enqueued URLs:
.
.IP
\fBsqlserver://test\.mycompany\.com:1433/WWII_Navy/?key\-val=0&\fR
.
.IP
\fBsqlserver://test\.mycompany\.com:1433/WWII_Navy/?key\-val=100&\fR
.
.IP
\fBsqlserver://test\.mycompany\.com:1433/WWII_Navy/?key\-val=200&\fR
.
.IP
While testing the following URL will show the data retrieved from row 43:
.
.IP
\fBsqlserver://test\.mycompany\.com:1433/WWII_Navy/?per=1&key\-val=43\fR
.
.IP "\(bu" 4
\fBhops\fR \- Internal use only\.
.
.IP "\(bu" 4
\fBdefault\-allow\fR \- Internal use only\.
.
.IP "\(bu" 4
\fBuser\-password\fR \- Credentials for the database system\. The username and password need to be separated by a \fB:\fR, and the password must be encrypted with the vcrypt program that ships with the Data Crawler\. For example \fBusername:[[vcrypt/3]]passwordstring\fR\.
.
.IP "\(bu" 4
\fBmax\-data\-size\fR \- Maximum size of the data for a document\. This is the largest block of memory that will be loaded at one time\. Only increase this limit if you have sufficient memory on your computer\.
.
.IP "\(bu" 4
\fBfilter\-exact\-duplicates\fR \- Internal use only\.
.
.IP "\(bu" 4
\fBjdbc\-class\fR (Extender option) \- When specified, this string will override the JDBC class used by the connector when \fB(other)\fR is chosen as the database system\.
.
.IP "\(bu" 4
\fBconnection\-string\fR (Extender option) \- When specified, this string will override the automatically generated JDBC connection string\. This allows you to provide more detailed configuration about the database connection, such as load\-balancing or SSL connections\. For example: \fBjdbc:netezza://127\.0\.0\.1:5480/databasename\fR\.
.
.IP "\(bu" 4
\fBsave\-frequency\-for\-resume\fR (Extender option) \- Specifies the name of a column or associated label, in order to be able to resume a crawl or do a partial refresh\. The seed saves the name of this column at regular intervals as it proceeds with the crawl, and saves it again once the last row of your database has been crawled\. When resuming the crawl or refreshing it, the crawl begins with the row that is identified in the saved value for this field\.
.
.IP "" 0
.
.SS "Configuring the CMIS Crawl Seed"
The following values can be configured for the CMIS crawl seed file\. To set these values, open the file \fBconfig/seeds/cmis\-seed\.conf\fR and modify the following values specific to your use cases:
.
.IP "\(bu" 4
\fBurl\fR \- The URL of a folder from the CMIS repository to be used as a starting point of the crawl, for example:
.
.IP "\(bu" 4
\fBcmis://alfresco\.test\.com:8080/alfresco/cmisatom?folderToProcess=workspace://SpacesStore/guid\fR To crawl from the root folder, you need to give the URL as:
.
.IP "\(bu" 4
\fBcmis://alfresco\.test\.com:8080/alfresco/cmisatom?folderToProcess=\fR
.
.IP "" 0

.
.IP "\(bu" 4
\fBat\fR \- Unused option\.
.
.IP "\(bu" 4
\fBdefault\-allow\fR \- Internal use only\.
.
.IP "" 0
.
.SS "Configuring the Samba Crawl Seed"
The following values can be configured for the Samba crawl seed file\. To set these values, open the file \fBconfig/seeds/samba\-seed\.conf\fR and modify the following values specific to your use cases:
.
.IP "\(bu" 4
\fBurl\fR \- A newline\-separated list of shares to crawl, for example:
.
.IP "\(bu" 4
\fBsmb://share\.test\.com/office\fR
.
.IP "\(bu" 4
\fBsmb://share\.test\.com/cash/money/change\fR
.
.IP "\(bu" 4
\fBsmb://share\.test\.com/C$/Program Files\fR
.
.IP "" 0

.
.IP "\(bu" 4
\fBhops\fR \- Internal use only\.
.
.IP "\(bu" 4
\fBdefault\-allow\fR \- Internal use only\.
.
.IP "" 0
.
.SS "Configuring the SharePoint Crawl Seed"
The following additional values can be configured for the SharePoint crawl seed file\. To set these values, open the file \fBconfig/seeds/sharepoint\-seed\.conf\fR and modify the following values specific to your use cases:
.
.IP "\(bu" 4
\fBurl\fR \- A newline\-separated list of SharePoint web applications or site collections to crawl, for example:
.
.IP "\(bu" 4
\fBio\-sp://a\.com\fR
.
.IP "\(bu" 4
\fBio\-sp://b\.com:83/site\fR
.
.IP "\(bu" 4
\fBio\-sp://c\.com/site2\fR
.
.IP "" 0
.
.IP
The sub\-sites of these sites will also be crawled (unless they are excluded by other crawling rules)\.
.
.IP "\(bu" 4
\fBfilter\-url\fR \- A newline\-separated list of SharePoint web applications or site collections to crawl, for example:
.
.IP "\(bu" 4
\fBhttp://a\.com\fR
.
.IP "\(bu" 4
\fBhttp://b\.com:83/site\fR
.
.IP "\(bu" 4
\fBhttp://c\.com/site2\fR
.
.IP "" 0

.
.IP "\(bu" 4
\fBhops\fR \- Internal use only\.
.
.IP "\(bu" 4
\fBn\-concurrent\-requests\fR \- Internal use only\.
.
.IP "\(bu" 4
\fBdelay\fR \- Internal use only\.
.
.IP "\(bu" 4
\fBdefault\-allow\fR \- Internal use only\.
.
.IP "\(bu" 4
\fBseed\-protocol\fR \- Sets the seed protocol for children of the site collection\. Necessary when the site collection\'s protocol is SSL, HTTP, or HTTPS\. This value must be set the same as the site collection\'s protocol\.
.
.IP "" 0
.
.SS "Configuring the Box Seed"
The following values can be configured for the Box crawl seed file\. To set these values, open the file \fBconfig/seeds/box\-seed\.conf\fR and specify the following values specific to your use cases:
.
.IP "\(bu" 4
\fBurl\fR \- The URL to be used as the starting point of the crawl\. The default value is \fBbox://app\.box\.com/\fR\.
.
.IP "\(bu" 4
\fBdefault\-allow\fR \- Internal use only\.
.
.IP "" 0
.
.SH "SEE ALSO"
crawler(1)
.
.P
vcrypt(1)
.
.P
crawler\.conf(5)
.
.P
crawler\-options\.conf(5)
.
.P
orchestration_service\.conf(5)
