.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ORCHESTRATION_SERVICE" "5" "March 2017" "IBM " "IBM Data Crawler Manual"
The orchestration service tells the crawler how to manage crawled files\. Default options can be changed directly by opening the \fBconfig/orchestration/orchestration\-service\.conf\fR file, and modifying the following values specific to your use case:
.
.IP "\(bu" 4
\fBhttp_timeout\fR \- The timeout, in seconds, for the document read/index operation; the default is \fB585\fR\.
.
.IP "\(bu" 4
\fBconcurrent_upload_connection_limit\fR \- The number of simultaneous connections allowed for uploading documents; the default is \fB10\fR\. Generally, this number should be greater than, or equal to, the \fBoutput_limit\fR set when configuring crawl options\.
.
.IP "\(bu" 4
\fBbase_url\fR \- The URL that your crawled documents will be sent to\.
.
.IP "\(bu" 4
\fBendpoint\fR \- The location of your crawled document collection at the \fBbase\-url\fR\.
.
.IP "\(bu" 4
\fBusername\fR \- Username to authenticate to the \fBendpoint\fR location\.
.
.IP "\(bu" 4
\fBpassword\fR \- Password to authenticate to the \fBendpoint\fR location\. \fBImportant\fR \- Do \fBNOT\fR use the vcrypt program shipped with the Data Crawler to encrypt this password\.
.
.IP "\(bu" 4
\fBconfig_file\fR \- The configuration file that the orchestration service uses\.
.
.IP "" 0
.
.P
The Orchestration Service Output Adapter can send statistics in order for IBM to better understand and serve its users\. The following options can be set for the \fBsend_stats\fR variable: * \fBjvm\fR \- Java Virtual Machine (JVM) statistics sent include the Java vendor and version, as reported by the JVM used to execute the data crawler\. Value is either \fBtrue\fR or \fBfalse\fR\. * \fBos\fR \- Operating system (OS) statistics sent include OS name, version, and architecture, as reported by the JVM used to execute the data crawler\. Value is either \fBtrue\fR or \fBfalse\fR\.
.
.SH "SEE ALSO"
crawler(1)
.
.P
vcrypt(1)
.
.P
crawler\.conf(5)
.
.P
crawler\-options\.conf(5)
.
.P
crawler\-seed\.conf(5)
